// ===== Bilingual content store — WLSN · Shami Wilson =====

const CONTENT = {
  en: {
    nav: { services: "Services", process: "Process", stack: "Stack", pricing: "Pricing", estimator: "AI Estimator", contact: "Contact" },
    ctaPrimary: "Start a project",
    ctaSecondary: "Book a call",
    hero: {
      eyebrow: "AVAILABLE FOR NEW PROJECTS · Q2 2026",
      title1: "Software,",
      title2: "systems,",
      title3: "and ",
      titleAccent: "AI",
      title4: " that ",
      title5: "actually ship.",
      sub: "Independent IT consultant based in Zürich. I build web tools, dashboards, automations and AI integrations — plus the compliance plumbing that banks actually need. One person, end-to-end, no agency markup.",
    },
    stats: [
      { num: "5+", lbl: "Years in IT" },
      { num: "Big 4", lbl: "Consulting background" },
      { num: "< 48h", lbl: "Response time" },
      { num: "CH / EU", lbl: "Timezone friendly" },
    ],
    servicesLabel: "What I do",
    servicesTitle: "From first idea to live in production.",
    servicesDesc: "Pick a single slice or a full build. I work alone on focused engagements and bring in trusted specialists when scope demands it.",
    services: [
      { tag: "CORE", title: "Web development", desc: "Clean, fast marketing sites, landing pages and small web apps. Performance-first, easy to hand off and maintain.", stack: ["Next.js", "React", "Astro", "Tailwind"] },
      { tag: "CORE", title: "Web apps & dashboards", desc: "Custom dashboards, admin panels and data tools that replace a pile of spreadsheets with one clean interface.", stack: ["React", "TypeScript", "Postgres", "Supabase"] },
      { tag: "AI", title: "AI integration", desc: "Chatbots, document processors, smart search, auto-classifiers — built with Claude or GPT and wired into your existing workflow.", stack: ["Claude API", "GPT-4", "RAG", "LangChain"] },
      { tag: "CORE", title: "Database design", desc: "Schema design, query optimisation, migrations and backups. Messy data turned into something you can actually query.", stack: ["PostgreSQL", "MySQL", "Supabase", "Prisma"] },
      { tag: "AI", title: "Workflow automation", desc: "Connecting the tools you already pay for. Form → CRM → invoice → Slack — running by itself, no more manual steps.", stack: ["n8n", "Zapier", "Make", "Python"] },
      { tag: "CORE", title: "Data analysis & reports", desc: "Ad-hoc SQL, automated weekly reports, PDF exports. Pulling useful signal out of the data your tools already collect.", stack: ["SQL", "Python", "Power BI", "Sheets"] },
      { tag: "CORE", title: "RegTech & compliance", desc: "Specialist knowledge from enterprise banking. CRS/FATCA reporting, multishore tax data pipelines, automated validation and reconciliation at scale.", stack: ["CRS/FATCA", "Tax Reporting", "ETL", "Banking"] },
      { tag: "CORE", title: "Custom internal tools", desc: "The one tool your team needs but no SaaS sells. Built in weeks, not quarters — tailored to your exact process.", stack: ["React", "Retool", "Airtable", "Claude API"] },
      { tag: "CORE", title: "IT consulting", desc: "Second opinion on stack choices, architecture reviews, vendor assessment. Straight answers, no upsell.", stack: ["Advisory", "Audits", "Reviews"] },
    ],
    processLabel: "How I work",
    processTitle: "Four steps, no mystery.",
    processDesc: "Clear scope, fast loops, working software every step of the way. You always know what's happening and what it costs.",
    process: [
      { num: "01", title: "Discovery call", desc: "30 minutes, free. What are you trying to solve, who is it for, and what's the smallest useful thing we could ship.", duration: "30 min · free" },
      { num: "02", title: "Scope & estimate", desc: "Written proposal with a price range, milestones and a timeline. Fixed price where possible, time-and-materials where it isn't.", duration: "2–3 days" },
      { num: "03", title: "Build in slices", desc: "Weekly updates, a live staging link, short walkthroughs. You see progress, not just promises.", duration: "1–8 weeks" },
      { num: "04", title: "Ship & support", desc: "Handover docs, a README a human can read, and 30 days of included support. Retainer available if you need ongoing help.", duration: "ongoing" },
    ],
    stackLabel: "Stack & tools",
    stackTitle: "Modern, boring, proven.",
    stackDesc: "I pick the simplest thing that will still be running in three years. No framework-of-the-week energy.",
    stack: [
      { title: "Frontend", items: ["React / Next.js", "Astro", "TypeScript", "Tailwind CSS", "HTML / CSS"] },
      { title: "Backend", items: ["Node.js", "Python", "Postgres / Supabase", "REST & GraphQL", "Excel / VBA"] },
      { title: "AI & Automation", items: ["Claude API", "OpenAI API", "n8n / Zapier", "LangChain / RAG", "Vector DBs"] },
      { title: "Data & Infra", items: ["Power BI", "SQL", "Docker", "Vercel / Netlify", "Cloudflare"] },
    ],
    pricingLabel: "Pricing",
    pricingTitle: "Project-based, transparent ranges.",
    pricingDesc: "Every project is quoted in writing after a discovery call. These ranges cover the majority of what I build.",
    pricing: [
      {
        plan: "STARTER",
        name: "Automation & integration",
        range: "CHF 500–2k",
        timeline: "1–2 weeks",
        features: [
          "Workflow automation (n8n / Zapier / Python)",
          "API connection between two or more tools",
          "Simple AI integration (chatbot, classifier)",
          "Scheduled data pipeline or report",
        ],
      },
      {
        plan: "STANDARD",
        name: "Web app or custom tool",
        range: "CHF 2k–6k",
        timeline: "2–6 weeks · weekly updates",
        features: [
          "Internal dashboard, admin panel or customer portal",
          "Landing page with CMS and contact flow",
          "AI-powered document processor or data tool",
          "Full-stack web application (MVP scope)",
        ],
        featured: true,
        badge: "MOST COMMON",
      },
      {
        plan: "COMPLEX",
        name: "Enterprise & compliance",
        range: "CHF 6k+",
        timeline: "scoped per engagement",
        features: [
          "Multi-module automation or reporting systems",
          "CRS / FATCA compliance architecture",
          "Long-term build and maintain retainer",
          "Team training and full documentation",
        ],
      },
    ],
    estLabel: "Live AI demo",
    estTitle: "Try my AI project estimator.",
    estDesc: "This widget runs live on the same Claude API I'd integrate into your product. Describe what you want to build — it returns a ballpark scope, timeline and price range. This exact pattern works well inside an internal tool or client portal.",
    est: {
      descLabel: "Describe your project",
      descPlaceholder: "e.g. A small portal where our sales team logs client calls, tags them by outcome, and I can pull a weekly summary report. Should have a simple admin view.",
      typeLabel: "Project type",
      types: ["Landing / website", "Web app / dashboard", "AI integration", "Automation", "Not sure yet"],
      urgencyLabel: "Timeline",
      urgency: ["ASAP", "1–2 months", "3+ months", "Exploring"],
      btn: "Estimate with Claude",
      btnLoading: "Thinking…",
      emptyState: "Your estimate will appear here. Generated live by Claude — the same API I'd integrate into your project.",
      rangeLbl: "ESTIMATED RANGE",
      timelineLbl: "TIMELINE",
      complexityLbl: "COMPLEXITY",
      scopeLbl: "LIKELY SCOPE",
      notesLbl: "NOTES",
    },
    contactLabel: "Get in touch",
    contactTitle: "Two short steps to find out if we fit.",
    contactDesc: "Pick a slot or send a few lines. Whichever is less effort.",
    form: {
      name: "Name",
      email: "Email",
      company: "Company (optional)",
      budget: "Budget range",
      budgetOptions: ["Under CHF 1k", "CHF 1k–3k", "CHF 3k–8k", "CHF 8k–20k", "CHF 20k+", "Not sure yet"],
      message: "What are you trying to build?",
      messagePh: "A few lines is enough. I'll reply within 48h.",
      submit: "Send enquiry",
      submitted: "Thanks — I'll reply within 48h.",
    },
    book: {
      title: "Book a 30-minute discovery call",
      desc: "Free, no agenda needed. We figure out if there's a fit and what the next concrete step looks like.",
      timezone: "All times CET · 30 min · free",
      confirm: "Confirm slot",
      confirmed: "Slot reserved — check your inbox.",
    },
    slots: [
      { day: "MON", date: "Apr 20", time: "10:00" },
      { day: "MON", date: "Apr 20", time: "14:30" },
      { day: "TUE", date: "Apr 21", time: "09:00" },
      { day: "WED", date: "Apr 22", time: "11:30" },
      { day: "THU", date: "Apr 23", time: "15:00" },
      { day: "FRI", date: "Apr 24", time: "10:30" },
    ],
    footer: {
      tagline: "Independent IT & AI services from Zürich. Built, shipped and maintained by one person who actually answers.",
      cols: [
        { h: "Services", links: ["Web development", "Web apps", "AI integration", "Automation", "RegTech"] },
        { h: "Info", links: ["Process", "Pricing", "Stack", "Contact"] },
        { h: "Contact", links: ["shami@wlsn.ch", "LinkedIn", "Book a call"] },
      ],
      bottom: "© 2026 WLSN · Shami Wilson · Zürich, CH · Built with HTML, coffee and Claude.",
    },
  },

  de: {
    nav: { services: "Leistungen", process: "Ablauf", stack: "Stack", pricing: "Preise", estimator: "KI-Rechner", contact: "Kontakt" },
    ctaPrimary: "Projekt starten",
    ctaSecondary: "Termin buchen",
    hero: {
      eyebrow: "VERFÜGBAR FÜR NEUE PROJEKTE · Q2 2026",
      sub: "Unabhängiger IT-Berater aus Zürich. Ich baue Web-Tools, Dashboards, Automatisierungen und KI-Integrationen — und kenne mich mit Compliance-Infrastruktur aus dem Bankensektor aus. Eine Person, durchgängig, ohne Agenturaufschlag.",
    },
    heroSub: "Unabhängiger IT-Berater aus Zürich. Ich baue Web-Tools, Dashboards, Automatisierungen und KI-Integrationen — und kenne mich mit Compliance-Infrastruktur aus dem Bankensektor aus. Eine Person, durchgängig, ohne Agenturaufschlag.",
    stats: [
      { num: "5+", lbl: "Jahre IT-Erfahrung" },
      { num: "Big 4", lbl: "Consulting-Hintergrund" },
      { num: "< 48h", lbl: "Antwortzeit" },
      { num: "CH / EU", lbl: "Zeitzonen-freundlich" },
    ],
    servicesLabel: "Was ich mache",
    servicesTitle: "Von der ersten Idee bis live in Produktion.",
    servicesDesc: "Ein einzelnes Teilstück oder der komplette Build. Ich arbeite allein bei fokussierten Projekten und hole Spezialisten dazu, wenn der Umfang es verlangt.",
    services: [
      { tag: "CORE", title: "Web-Entwicklung", desc: "Saubere, schnelle Marketing-Sites, Landing-Pages und kleine Web-Apps. Performance-first, einfach zu übergeben und zu pflegen.", stack: ["Next.js", "React", "Astro", "Tailwind"] },
      { tag: "CORE", title: "Web-Apps & Dashboards", desc: "Custom Dashboards, Admin-Panels und Daten-Tools, die einen Haufen Tabellen durch eine saubere Oberfläche ersetzen.", stack: ["React", "TypeScript", "Postgres", "Supabase"] },
      { tag: "AI", title: "KI-Integration", desc: "Chatbots, Dokumentenverarbeitung, intelligente Suche, Auto-Klassifizierung — mit Claude oder GPT in deinen bestehenden Workflow integriert.", stack: ["Claude API", "GPT-4", "RAG", "LangChain"] },
      { tag: "CORE", title: "Datenbank-Design", desc: "Schemadesign, Query-Optimierung, Migrationen und Backups. Chaotische Daten werden abfragbar.", stack: ["PostgreSQL", "MySQL", "Supabase", "Prisma"] },
      { tag: "AI", title: "Workflow-Automatisierung", desc: "Die Tools verbinden, für die du schon zahlst. Formular → CRM → Rechnung → Slack — vollautomatisch, ohne manuelle Schritte.", stack: ["n8n", "Zapier", "Make", "Python"] },
      { tag: "CORE", title: "Datenanalyse & Reports", desc: "Ad-hoc SQL, automatisierte Wochenreports, PDF-Exporte. Nützliches Signal aus den Daten, die deine Tools ohnehin sammeln.", stack: ["SQL", "Python", "Power BI", "Sheets"] },
      { tag: "CORE", title: "RegTech & Compliance", desc: "Spezialwissen aus dem Enterprise-Banking. CRS/FATCA-Reporting, multishore Steuer-Datenpipelines, automatisierte Validierung und Abstimmung.", stack: ["CRS/FATCA", "Steuer-Reporting", "ETL", "Banking"] },
      { tag: "CORE", title: "Interne Tools", desc: "Das eine Tool, das dein Team braucht, aber kein SaaS verkauft. In Wochen statt Quartalen gebaut — zugeschnitten auf deinen genauen Prozess.", stack: ["React", "Retool", "Airtable", "Claude API"] },
      { tag: "CORE", title: "IT-Beratung", desc: "Zweite Meinung zu Stack-Entscheidungen, Architektur-Reviews, Lieferanten-Bewertung. Klare Antworten, kein Upsell.", stack: ["Beratung", "Audits", "Reviews"] },
    ],
    processLabel: "Wie ich arbeite",
    processTitle: "Vier Schritte, kein Mysterium.",
    processDesc: "Klarer Scope, schnelle Loops, funktionierende Software in jedem Schritt. Du weisst immer, was läuft und was es kostet.",
    process: [
      { num: "01", title: "Erstgespräch", desc: "30 Minuten, kostenlos. Welches Problem, für wen, was ist das kleinste nützliche Ding, das wir liefern können.", duration: "30 Min · kostenlos" },
      { num: "02", title: "Scope & Angebot", desc: "Schriftliches Angebot mit Preisrahmen, Meilensteinen und Timeline. Fixpreis wo möglich, Zeit und Material wo nötig.", duration: "2–3 Tage" },
      { num: "03", title: "In Schritten bauen", desc: "Wöchentliche Updates, Live-Staging-Link, kurze Walkthroughs. Du siehst Fortschritt, nicht nur Versprechen.", duration: "1–8 Wochen" },
      { num: "04", title: "Live & Support", desc: "Übergabe-Doku, ein README für Menschen, 30 Tage inklusive Support. Retainer optional für laufende Betreuung.", duration: "laufend" },
    ],
    stackLabel: "Stack & Tools",
    stackTitle: "Modern, langweilig, bewährt.",
    stackDesc: "Ich wähle das Einfachste, das in drei Jahren noch läuft. Kein Framework-der-Woche-Hype.",
    stack: [
      { title: "Frontend", items: ["React / Next.js", "Astro", "TypeScript", "Tailwind CSS", "HTML / CSS"] },
      { title: "Backend", items: ["Node.js", "Python", "Postgres / Supabase", "REST & GraphQL", "Excel / VBA"] },
      { title: "KI & Automation", items: ["Claude API", "OpenAI API", "n8n / Zapier", "LangChain / RAG", "Vektor-DBs"] },
      { title: "Daten & Infra", items: ["Power BI", "SQL", "Docker", "Vercel / Netlify", "Cloudflare"] },
    ],
    pricingLabel: "Preise",
    pricingTitle: "Projektbasiert, transparente Rahmen.",
    pricingDesc: "Jedes Projekt wird nach dem Erstgespräch schriftlich angeboten. Diese Rahmen decken die meisten meiner Projekte ab.",
    pricing: [
      {
        plan: "STARTER",
        name: "Automatisierung & Integration",
        range: "CHF 500–2k",
        timeline: "1–2 Wochen",
        features: [
          "Workflow-Automatisierung (n8n / Zapier / Python)",
          "API-Verbindung zwischen Tools",
          "Einfache KI-Integration (Chatbot, Klassifizierung)",
          "Geplante Datenpipeline oder Report",
        ],
      },
      {
        plan: "STANDARD",
        name: "Web-App oder internes Tool",
        range: "CHF 2k–6k",
        timeline: "2–6 Wochen · wöchentliche Updates",
        features: [
          "Dashboard, Admin-Panel oder Kundenportal",
          "Landing-Page mit CMS und Kontaktformular",
          "KI-gestütztes Dokumenten-Tool oder Datentool",
          "Full-Stack Web-App (MVP-Umfang)",
        ],
        featured: true,
        badge: "AM HÄUFIGSTEN",
      },
      {
        plan: "KOMPLEX",
        name: "Enterprise & Compliance",
        range: "CHF 6k+",
        timeline: "nach Vereinbarung",
        features: [
          "Mehrstufige Automatisierungs- oder Reporting-Systeme",
          "CRS / FATCA Compliance-Architektur",
          "Langfristiger Build-and-Maintain-Retainer",
          "Team-Training und vollständige Dokumentation",
        ],
      },
    ],
    estLabel: "Live KI-Demo",
    estTitle: "Probier meinen KI-Projektrechner.",
    estDesc: "Dieses Widget läuft live auf derselben Claude-API, die ich in dein Produkt integrieren würde. Beschreibe dein Vorhaben — du bekommst eine grobe Einschätzung zu Scope, Timeline und Budget.",
    est: {
      descLabel: "Projekt beschreiben",
      descPlaceholder: "z.B. Ein kleines Portal, in dem unser Vertriebsteam Kundengespräche erfasst, nach Ergebnis taggt und ich wöchentlich einen Zusammenfassungsreport abrufen kann.",
      typeLabel: "Projekttyp",
      types: ["Landing / Website", "Web-App / Dashboard", "KI-Integration", "Automatisierung", "Noch unklar"],
      urgencyLabel: "Timeline",
      urgency: ["ASAP", "1–2 Monate", "3+ Monate", "Erkundung"],
      btn: "Mit Claude schätzen",
      btnLoading: "Denke nach…",
      emptyState: "Deine Einschätzung erscheint hier. Live generiert von Claude — dieselbe API, die ich in dein Projekt integrieren würde.",
      rangeLbl: "GESCHÄTZTER RAHMEN",
      timelineLbl: "TIMELINE",
      complexityLbl: "KOMPLEXITÄT",
      scopeLbl: "WAHRSCHEINLICHER SCOPE",
      notesLbl: "NOTIZEN",
    },
    contactLabel: "Kontakt",
    contactTitle: "Zwei kurze Schritte — passt's oder nicht.",
    contactDesc: "Slot auswählen oder ein paar Zeilen schicken. Was weniger Aufwand ist.",
    form: {
      name: "Name",
      email: "E-Mail",
      company: "Unternehmen (optional)",
      budget: "Budget-Rahmen",
      budgetOptions: ["Unter CHF 1k", "CHF 1k–3k", "CHF 3k–8k", "CHF 8k–20k", "CHF 20k+", "Noch unklar"],
      message: "Was möchtest du bauen?",
      messagePh: "Ein paar Zeilen genügen. Ich antworte innerhalb 48 Std.",
      submit: "Anfrage senden",
      submitted: "Danke — ich melde mich innerhalb 48 Std.",
    },
    book: {
      title: "30-Minuten-Erstgespräch buchen",
      desc: "Kostenlos, ohne Agenda. Wir klären, ob's passt und wie der nächste konkrete Schritt aussieht.",
      timezone: "Alle Zeiten MEZ · 30 Min · kostenlos",
      confirm: "Slot bestätigen",
      confirmed: "Slot reserviert — check deinen Posteingang.",
    },
    slots: [
      { day: "MO", date: "20. Apr", time: "10:00" },
      { day: "MO", date: "20. Apr", time: "14:30" },
      { day: "DI", date: "21. Apr", time: "09:00" },
      { day: "MI", date: "22. Apr", time: "11:30" },
      { day: "DO", date: "23. Apr", time: "15:00" },
      { day: "FR", date: "24. Apr", time: "10:30" },
    ],
    footer: {
      tagline: "Unabhängige IT- & KI-Services aus Zürich. Gebaut, deployed und gewartet von einer Person, die das Telefon abnimmt.",
      cols: [
        { h: "Leistungen", links: ["Web-Entwicklung", "Web-Apps", "KI-Integration", "Automatisierung", "RegTech"] },
        { h: "Info", links: ["Ablauf", "Preise", "Stack", "Kontakt"] },
        { h: "Kontakt", links: ["shami@wlsn.ch", "LinkedIn", "Termin buchen"] },
      ],
      bottom: "© 2026 WLSN · Shami Wilson · Zürich · Gebaut mit HTML, Kaffee und Claude.",
    },
  },
};

window.CONTENT = CONTENT;
